FROM rpimage/platformio:3.1.0

MAINTAINER Roberto Valentini <valantin89 (at) gmail [dot] com>

RUN platformio platform install espressif8266  --with-package=tool-esptool --with-package=framework-arduinoespressif8266
